add_manual_task:
  name: Manuelle Aufgabe hinzufügen
  description: Lässt die KI eine neue Aufgabe analysieren und als unterteilte To-dos eintragen.
  fields:
    summary:
      description: Kurztitel der Aufgabe.
      example: Solaranlage reparieren
      required: true
      selector:
        text:
    description:
      description: Zusätzliche Details oder Kontext.
      example: Wechselrichter zeigt Fehlercode an
      required: false
      selector:
        text:
          multiline: true
    due:
      description: Fälligkeitsdatum als ISO-8601-String.
      example: "2024-07-01T18:00:00+02:00"
      required: false
      selector:
        datetime:
    household_context:
      description: Zusätzliche Informationen zum Haushalt (z.B. Zuständigkeiten).
      required: false
      selector:
        text:
    entry_id:
      description: Optionale Config-Entry-ID, falls mehrere Instanzen vorhanden sind.
      required: false
      selector:
        text:
mark_task_in_progress:
  name: Aufgabe als "In Bearbeitung" markieren
  description: Setzt einen To-do-Eintrag (Eltern- oder Unteraufgabe) in den Status "In Bearbeitung".
  fields:
    uid:
      description: Die UID des To-dos, wie in der Liste angezeigt.
      example: 5b3c9ef6-6a7d-4c55-9d60-6b66d1c95f44
      required: true
      selector:
        text:
    entry_id:
      description: Optionale Config-Entry-ID, falls mehrere Instanzen vorhanden sind.
      required: false
      selector:
        text:
