add_manual_task:
  name: Manuelle Aufgabe hinzufügen
  description: Lässt die KI eine neue Aufgabe analysieren und als unterteilte To-dos eintragen.
  fields:
    summary:
      description: Kurztitel der Aufgabe.
      example: Solaranlage reparieren
      required: true
      selector:
        text:
    description:
      description: Zusätzliche Details oder Kontext.
      example: Wechselrichter zeigt Fehlercode an
      required: false
      selector:
        text:
          multiline: true
    due:
      description: Fälligkeitsdatum als ISO-8601-String.
      example: "2024-07-01T18:00:00+02:00"
      required: false
      selector:
        datetime:
    household_context:
      description: Zusätzliche Informationen zum Haushalt (z.B. Zuständigkeiten).
      required: false
      selector:
        text:
    entry_id:
      description: Optionale Config-Entry-ID, falls mehrere Instanzen vorhanden sind.
      required: false
      selector:
        text:
